// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQyX3Mdxvd7A_e9jxbVT_SbfjE4bYIATw',
    appId: '1:514598555350:web:a8f16bf5dc96c53400c377',
    messagingSenderId: '514598555350',
    projectId: 'fir-project-st81',
    authDomain: 'fir-project-st81.firebaseapp.com',
    storageBucket: 'fir-project-st81.appspot.com',
    measurementId: 'G-WSKZZNE5WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWKE-VRUffzHJDJtEO2Bl2azE-rM3Dz0',
    appId: '1:514598555350:android:fac1c4d3d472db1b00c377',
    messagingSenderId: '514598555350',
    projectId: 'fir-project-st81',
    storageBucket: 'fir-project-st81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtoewwFBaAhT1IWtjQ4uqr-triL9XnjGg',
    appId: '1:514598555350:ios:963ae91e3aabd9b400c377',
    messagingSenderId: '514598555350',
    projectId: 'fir-project-st81',
    storageBucket: 'fir-project-st81.appspot.com',
    iosClientId: '514598555350-8b4hl1ndpg0a8k4ceun0c7o1ciq4hpb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondProjectFireabse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtoewwFBaAhT1IWtjQ4uqr-triL9XnjGg',
    appId: '1:514598555350:ios:963ae91e3aabd9b400c377',
    messagingSenderId: '514598555350',
    projectId: 'fir-project-st81',
    storageBucket: 'fir-project-st81.appspot.com',
    iosClientId: '514598555350-8b4hl1ndpg0a8k4ceun0c7o1ciq4hpb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondProjectFireabse',
  );
}
